### PR TITLE
Implementing (approximately) fulltext search

### PR DESCRIPTION
**Pull request by donmccurdy**
Wasn't sure where help would be most useful to you all, but this at least partially addresses https://github.com/code4sac/wicit/issues/13.

If you need more performance there are some lightweight options like Sphinx Realtime indexes, but for the dataset in the repository this seems to work nicely.

### CODE REVIEW

**Comment by jesserosato** [comment]
@donmccurdy Thank you! Really nicely done, very concise. I'll close #13 and open a new issue for client-side UI to support this. Again, thanks for contributing!

**Comment by jesserosato** [comment]
[Issue for client-side UI](https://github.com/code4sac/wicit/issues/28)

**Comment by jesserosato** [comment]
OST, @donmccurdy I'm gonna keep #13 open as a place for discussion on the feature in general, and we'll spin up new issues as needed for more specific tasks as they arise.

**Comment by donmccurdy** [comment]
Sure thing, sounds good!

**Pull request merged**
